"""
Django settings for intellodge project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r$xf)fz%ek8*!vwdk0!4lz-61ae@!x%+ilu-$ygx)m$1&6i^!i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['intellodge.us-east-1.elasticbeanstalk.com']


# Application definition

INSTALLED_APPS = [
    # below are the applciation urls of Intellodge app
    'intelrev.apps.IntelrevConfig',
    'intelroom.apps.IntelroomConfig',
    'intelbookings.apps.IntelbookingsConfig',
    'intelrevenue.apps.IntelrevenueConfig',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intellodge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intellodge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files 

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "intelrev" / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"  # used for collectstatic


LOGIN_URL = '/login/'               # where the @login_required redirects
LOGIN_REDIRECT_URL = '/'            # after successful login
LOGOUT_REDIRECT_URL = '/login/'     # after logout go to login


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://*.vfs.cloud9.us-east-1.amazonaws.com',
]

# Custom Backend authentication for the DynamoDB
AUTHENTICATION_BACKENDS = [
    'authapp.cognito_auth.CognitoAuthenticationBackend', # for cognito authentication for the dynamodb
    'django.contrib.auth.backends.ModelBackend', 
]

# Storing the below details securely: from the Cognito setup
COGNITO_USER_POOL_ID = "us-east-1_qC5AK66Ng"
COGNITO_CLIENT_ID = "2be3nlsi7tb15kle06kh4bc51t"
COGNITO_REGION = "us-east-1"

# below is the bucket name from S3
AWS_S3_BUCKET = "intellodge-room-images-demo-intelroom"